import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const local=process.env.TEST_BASE_URL || 'http://127.0.0.1:3123';
const origin='https://long2text.com';
const out=await mkdtemp(join(tmpdir(),'l2t-growth-'));
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']});
 // Serve the real built application under its production origin in an isolated
 // browser. No real GA/OCR/auth/payment calls or existing browser sessions.
 await context.route(origin+'/**',async r=>{
   const u=new URL(r.request().url());
   const res=await context.request.get(local+u.pathname+u.search);
   await r.fulfill({response:res});
 });
 let gaLoads=0,authenticated=false,failCheckout=false,failPrepare=false;
 await context.route('https://www.googletagmanager.com/**',r=>{gaLoads++;return r.fulfill({contentType:'application/javascript',body:'/* isolated GA transport stub */'});});
 await context.route(/google-analytics\.com/,r=>{throw Error('Unexpected live GA request: '+new URL(r.request().url()).pathname);});
 const page=await context.newPage();const errors=[],observed=[];page.on('pageerror',e=>errors.push(e.message));
 await page.exposeFunction('recordGrowth',detail=>observed.push(detail));
 await page.addInitScript(()=>window.addEventListener('l2t:analytics',e=>window.recordGrowth(e.detail)));
 await page.route('**/api/auth/session',r=>r.fulfill({json:authenticated?{user:{name:'Public test user'},expires:'2099-01-01'}:{}}));
 await page.route('**/api/auth/providers',r=>r.fulfill({json:{google:{id:'google',name:'Google',type:'oauth',signinUrl:origin+'/api/auth/signin/google',callbackUrl:origin+'/api/auth/callback/google'}}}));
 await page.route('**/api/auth/csrf',r=>r.fulfill({json:{csrfToken:'public-fixture'}}));
 await page.route('**/api/auth/signin/google*',r=>{authenticated=true;return r.fulfill({json:{url:origin+'/'}});});
 await page.route('**/api/correct',r=>r.fulfill({json:{enabled:false}}));
 await page.route('**/api/ocr',r=>r.request().method()==='GET'
   ?r.fulfill({status:failPrepare?503:200,json:{provider:'google'}})
   :r.fulfill({json:{success:true,blocks:Array.from({length:16},(_,i)=>({text:`Public sample paragraph ${i}. A document needs usable words and structure.`,confidence:99,x:30,y:30+i*80,width:600,height:28}))}}));
 await page.route('**/api/ocr-results',r=>r.fulfill({json:r.request().method()==='POST'?{id:'public-result'}:[]}));
 await page.route('**/api/checkout',r=>r.fulfill({status:failCheckout?503:200,json:failCheckout?{error:'Controlled checkout failure'}:{url:origin+'/?checkout_fixture=1'}}));
 const events=()=>page.evaluate(()=>Array.from(window.dataLayer||[],x=>Array.from(x)).filter(x=>x[0]==='event'));
 await page.goto(origin+'/privacy?utm_source=reddit&utm_campaign=markdown_test&private=DO_NOT_SEND');
 await page.getByRole('button',{name:'Enable optional analytics',exact:true}).waitFor();
 assert.equal(gaLoads,0);
 await page.getByRole('button',{name:'Enable optional analytics',exact:true}).click();
 await page.getByRole('button',{name:'Disable optional analytics',exact:true}).waitFor();
 await page.waitForFunction(()=>window.__l2tGrowthReady);
 assert.equal((await events())[0][2].l2t_source,'reddit');
 assert.ok(!JSON.stringify(await events()).includes('DO_NOT_SEND'));
 await page.goto(origin+'/long-screenshot-to-markdown-test');
 await page.waitForFunction(()=>window.__l2tGrowthReady);
 assert.equal((await events())[0][2].l2t_source,'reddit');
 await page.getByRole('link',{name:'screenshot-to-Markdown workflow',exact:true}).click();
 await page.locator('button').filter({hasText:'Upload screenshot'}).waitFor();
 await page.locator('input[type=file]').setInputFiles(new URL('../public/samples/en-chat.jpg',import.meta.url).pathname);
 await page.getByRole('button',{name:'Copy preview',exact:true}).waitFor();
 await page.getByRole('button',{name:/Sign in.*unlock/i}).scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>window.dataLayer.some(x=>x[1]==='paywall_view'));
 let e=await events();assert.equal(e.filter(x=>x[1]==='paywall_view').length,1);
 const ocr=e.find(x=>x[1]==='ocr_completed')[2];assert.equal(ocr.input_method,'file');assert.equal(ocr.result_access,'preview');assert.ok(ocr.duration_bucket);
 await page.getByRole('button',{name:'Copy preview',exact:true}).click();
 await page.waitForFunction(()=>window.dataLayer.some(x=>x[1]==='export_completed'));
 assert.equal((await events()).find(x=>x[1]==='export_completed')[2].result_access,'preview');
 await page.screenshot({path:join(out,'preview-mobile.png')});
 await page.getByRole('button',{name:/Sign in.*unlock/i}).scrollIntoViewIfNeeded();
 await page.screenshot({path:join(out,'paywall-mobile.png')});
 await page.getByRole('button',{name:/Sign in.*unlock/i}).click();
 await page.waitForURL(origin+'/');
 await page.waitForFunction(()=>window.dataLayer?.some(x=>x[1]==='login_success'));
 assert.equal((await events()).filter(x=>x[1]==='login_success').length,1);
 await page.locator('input[type=file]').setInputFiles(new URL('../public/samples/en-chat.jpg',import.meta.url).pathname);
 await page.getByRole('button',{name:'Copy preview',exact:true}).waitFor();
 failCheckout=true;
 await page.getByRole('button',{name:/^Unlock this image/}).click();
 await page.waitForFunction(()=>window.dataLayer.some(x=>x[1]==='checkout_failed'));
 assert.equal((await events()).find(x=>x[1]==='checkout_failed')[2].failure_stage,'checkout');
 failCheckout=false;
 await page.getByRole('button',{name:/^Unlock this image/}).click();
 await page.waitForURL('**/?checkout_fixture=1');
 assert.equal(observed.filter(e=>e.name==='begin_checkout').length,1);
 failPrepare=true;
 await page.locator('input[type=file]').setInputFiles(new URL('../public/samples/en-chat.jpg',import.meta.url).pathname);
 await page.waitForFunction(()=>window.dataLayer?.some(x=>x[1]==='ocr_failed'));
 assert.equal((await events()).find(x=>x[1]==='ocr_failed')[2].failure_stage,'prepare');
 await page.goto(origin+'/#pricing');
 await page.waitForFunction(()=>window.dataLayer?.some(x=>x[1]==='pricing_view'));
 await page.setViewportSize({width:320,height:844});
 await page.locator('#pricing').scrollIntoViewIfNeeded();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 await page.screenshot({path:join(out,'pricing-320.png')});
 await page.goto(origin+'/privacy');
 await page.getByRole('button',{name:'Disable optional analytics',exact:true}).click();
 await page.getByRole('button',{name:'Enable optional analytics',exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>sessionStorage.getItem('l2t-attribution-v1')),null);
 assert.equal(await page.evaluate(()=>!!window.dataLayer),false);
 await page.getByRole('heading',{name:'Analytics and cookies',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:join(out,'privacy-320.png')});
 assert.deepEqual(errors,[]);
 console.log('PASS: real built UI + opt-in, attribution, article, OCR bands/access, paywall, copy, login return, checkout failure/redirect, OCR failure, pricing, revocation; no live GA/auth/OCR/payment calls.');
 console.log('Screenshots:',out);
 await context.close();
}finally{await browser.close();}
